spring.application.name=apiGateWay

# for custom port number
server.port=8080


spring.cloud.gateway.routes[0].id=restaurant-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/restaurants/**